# This configuration file allows our pre-commit hooks to be used with pre-commit: http://pre-commit.com/

- id: terraform-fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format
  entry: bash /data/hooks/terraform-fmt.sh
  language: docker
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: terraform-validate
  name: Terraform validate
  description: Validates all Terraform configuration files
  entry: bash /data/hooks/terraform-validate.sh
  language: docker
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true

- id: tflint
  name: tflint
  description: Linter for Terraform source code
  entry: bash /data/hooks/tflint.sh
  language: docker
  files: \.tf$
  exclude: \.+.terraform\/.*$

- id: terragrunt-hclfmt
  name: Terragrunt hclfmt
  description: Rewrites all Terragrunt configuration files to a canonical format
  entry: bash /data/hooks/terragrunt-hclfmt.sh
  language: docker
  files: \.hcl$
  exclude: >
    (?x)^(
      .+\.terraform\/.*$|
      .+\.terragrunt-cache\/.*$|
    )$

- id: shellcheck
  name: Shellcheck Bash Linter
  description: Performs linting on bash scripts
  entry: bash /data/hooks/shellcheck.sh
  language: docker

- id: gofmt
  name: gofmt
  description: Gofmt formats Go programs
  entry: bash /data/hooks/gofmt.sh
  language: docker
  files: \.go$
  exclude: vendor\/.*$

- id: goimports
  name: goimports
  description: Goimports updates imports and formats in the same style as gofmt
  entry: bash /data/hooks/goimports.sh
  language: docker
  files: \.go$
  exclude: vendor\/.*$

- id: golint
  name: golint
  description: Golint is a linter for Go source code
  entry: bash /data/hooks/golint.sh
  language: docker
  files: \.go$
  exclude: vendor\/.*$

- id: yapf
  name: yapf
  description: yapf (Yet Another Python Formatter) is a python formatter from Google
  entry: bash /data/hooks/yapf.sh
  language: docker
  files: \.py$
  exclude: >
    (?x)^(
      \.tox\/.*$|
      __pycache__\/.*$
    )$

- id: helmlint
  name: helmlint
  description: Run helm lint, a linter for helm charts
  entry: bash /data/hooks/helmlint.sh
  language: docker
  files: \.((ya?ml)|(tpl))$
  require_serial: true

- id: markdown-link-check
  name: markdown-link-check
  description: Run markdown-link-check to check all the relative and absolute links in markdown docs.
  entry: bash /data/hooks/mdlink-check.sh
  language: docker
  files: \.md$
  exclude: vendor\/.*$

- id: check-terratest-skip-env
  name: check-terratest-skip-env
  description: Check all go source files for any uncommented os.Setenv calls setting a terratest SKIP environment.
  entry: bash /data/hooks/check_skip_env.py
  language: docker
  files: \.go$
